# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ feature/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEVELOP}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          script: |
            sudo apt-get -y install mysql-client
            sudo mkdir -p /var/www/wordpress/
            sudo chmod -R 775 /var/www/wordpress/
            sudo chown -R www-data: /var/www/wordpress/
            sudo usermod -aG www-data ubuntu
            cd /var/www/wordpress/
            git clone https://github.com/dextacy10-13/WordPress.git .
            wp config create --dbname=${{ secrets.WP_DB_NAME_DEVELOP }} --dbhost=${{ secrets.WP_DB_HOST_DEVELOP }} --dbuser=${{ secrets.WP_DB_USERNAME_DEVELOP }} --dbpass=${{ secrets.WP_DB_PASSWORD_DEVELOP }}
            whoami
            ls -al