# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          script: |
            sudo apt-get -y install mysql-client
            sudo mkdir -p /var/www/wordpress/
            sudo chmod -R 775 /var/www/wordpress/
            sudo chown -R www-data: /var/www/wordpress/
            sudo usermod -aG www-data ubuntu
            cd /var/www/wordpress/
            git clone https://github.com/dextacy10-13/WordPress.git .
            wp config create --dbname=${{ secrets.WP_DB_NAME_STAGING }} --dbprefix=${{ secrets.WP_DB_PREFIX_STAGING }} --dbhost=${{ secrets.WP_DB_HOST_STAGING }} --dbuser=${{ secrets.WP_DB_USERNAME_STAGING }} --dbpass=${{ secrets.WP_DB_PASSWORD_STAGING }}
            ls -al
